language: rust

branches:
  only:
    - master
    - staging
    - trying

rust:
  - 1.35.0
  - stable
  - nightly

if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

matrix:
  allow_failures:
    - rust: nightly

before_install: set -e

script:
  - cargo test --all

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  email:
    on_success: never
