language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly

before_install: set -e

install:
  - sh ci/install.sh

script:
  - sh ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
