[package]
authors = [
    "The Cortex-M Team <cortex-m@teams.rust-embedded.org>",
    "Jorge Aparicio <jorge@japaric.io>",
]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to Cortex-M processors"
documentation = "https://docs.rs/cortex-m"
keywords = ["arm", "cortex-m", "register", "peripheral"]
license = "MIT OR Apache-2.0"
name = "cortex-m"
readme = "README.md"
repository = "https://github.com/rust-embedded/cortex-m"
version = "0.6.7"
edition = "2018"

[dependencies]
aligned = "0.3.1"
bare-metal = { version = "0.2.0", features = ["const-fn"] }
volatile-register = "0.2.0"
bitfield = "0.13.2"
cortex_m_0_7 = { package = "cortex-m", version = "0.7.0" }

[features]
const-fn = []
cm7-r0p1 = ["cortex_m_0_7/cm7-r0p1"]
inline-asm = ["cortex_m_0_7/inline-asm"]
