on:
  push:
    branches-ignore:
      - "gh-readonly-queue/**"
  pull_request_target:
  merge_group:

name: Clippy check
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.number }}/head
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --features cortex-m/critical-section-single-core
